FROM nnurphy/ub:latest

RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      build-essential default-jdk \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN set -eux \
  ; for x in java metals \
  ; do nvim -u /etc/skel/.config/nvim/init.vim --headless +"CocInstall -sync coc-$x" +qa; done \
  \
  ; mkdir -p /opt/language-server/java \
  ; curl https://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.68.0-202012242230.tar.gz \
    | tar --no-same-owner -zxf - -C /opt/language-server/java \
  ; echo "let g:coc_user_config['java.jdt.ls.home'] = '/opt/language-server/java'" >> /etc/skel/.config/nvim/config.coc/lsp.vim \
  \
  #; npm config set registry https://registry.npm.taobao.org \
  ; npm cache clean -f

ENV SCALA_HOME=/opt/scala SCALA_VERSION=2.13.4
ENV PATH=${SCALA_HOME}/bin:$PATH

RUN set -ex \
  ; mkdir -p /usr/share/man/man1 \
  ; mkdir -p ${SCALA_HOME} \
  ; wget -q -O- https://downloads.lightbend.com/scala/$SCALA_VERSION/scala-$SCALA_VERSION.tgz \
      | tar xzf - -C ${SCALA_HOME} --strip-components=1
  #; rm -rf ${HOME}/.cache/coursier/*
